# Etapa 1: Build
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa 2: Nginx
FROM nginx:stable-alpine
# Copiamos nuestra config personalizada
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Copiamos los archivos de build
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]