# Dockerfile para el Frontend (Producción)
FROM nginx:stable-alpine

# Copiamos la carpeta build generada localmente a la carpeta de Nginx
COPY ./build /usr/share/nginx/html

# Copiamos una configuración de Nginx si tienes una (opcional)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]